moderate the cos route of contest in static.ts
eesast/api pull request #1305
Opened 2024-03-24 13:02 UTC by zou-y-t

2024-03-24 13:40 UTC, xiangmy21 requested changes

2024-03-24 13:40 UTC, xiangmy21 commented on src/routes/static.ts
>          if (role == 'counselor' || role == 'root' || role == 'admin') {
把 root 这个删掉，现在没有这个role了

2024-03-24 13:40 UTC, xiangmy21 commented on src/routes/static.ts
>          if (role == 'counselor' || role == 'root' || role == 'admin') {
counselor也删掉吧，不应该给所有权限的

2024-03-25 10:15 UTC, FranGuam commented on src/routes/static.ts
`/:name/notice/*`是不是没加呀，不要忘记啦 @zou-y-t

2024-03-28 04:41 UTC, xiangmy21 requested changes
记得改一下authenticate.ts，在!authHeader的地方加一个返回匿名用户

2024-03-28 04:41 UTC, xiangmy21 commented on src/routes/static.ts
>          user_uuid = payload.uuid;
这一段开头的地方加上authenticate()中间件，把解头的这部分去掉，另外改一下authenticate.ts，在!authHeader的地方加一个req.auth = {匿名用户}

2024-03-28 10:22 UTC, zou-y-t commented on src/routes/static.ts
>          user_uuid = payload.uuid;
改好啦

2024-03-28 10:59 UTC, xiangmy21 approved these changes

2024-03-28 11:00 UTC, merged