Completed arena and competition backend interface, rewrote and updated docker_queue
eesast/api pull request #1311
Opened 2024-04-04 14:21 UTC by zzdhybthu

🤗为了使接口更通用一些，代码量明显多了不少（）
测试是分步进行的，试了几种情况，能按预期进行。更完整的测试也许得等一下 THUAI7 的 2/3个镜像。

一些对规则的微小改动在web里提pr吧。

2024-04-04 15:02 UTC, zzdhybthu commented
关于比赛结果，不知道格式是什么样的，暂时没有修改这项。也许可以让前端通过比较分数来判断输赢。

2024-04-04 15:04 UTC, zzdhybthu commented
关于日志文件，看到群里说可能会很大。我的做法是把所有 位于playback 目录下的文件都上传到cos，把决定权留给队式组。如果他们把日志放在这个目录下，就会上传。

2024-04-04 15:08 UTC, zzdhybthu commented
代码可能有些复杂。没写注释。可以把console.debug和log中的内容以及变量的命名作为注释看待。代码比去年的版本多出来不少的原因在于通用性提高了很多，还有就是需要检查的内容也很多。理论上现在可以支持任意多队伍、任意不同的teamlabel，任意不同的playerlabel打混战（）

2024-04-04 15:16 UTC, zzdhybthu commented
> 还没看，但是太🐂了

写了两整天了😭😭

2024-04-04 15:35 UTC, zzdhybthu commented
还有关于几个需要手动调节的变量：
一个是服务器存放的最大文件数目。目前删文件的逻辑是，会把可执行文件长期存储在code/team_id目录下，每次开天梯对战时，先从cos下载不存在的文件，然后检查文件总数，如果文件数目超过x，删除当前比赛不使用且最古老的y个文件。x和y需要手动调节。
一个是比赛是否开放观战端口,目前天梯默认开放，比赛默认不开放。开放的话会启动envoy容器，并更新port。应该得看情况调节。
还有 memory 限制，目前延续了去年的配置。
以及比赛最长时间、容器强制销毁时间等

2024-04-04 15:37 UTC, zzdhybthu commented
另外关于后端存储目录，放在了
${base_directory}/${contest_name}/arena/${room_id}/source
${base_directory}/${contest_name}/arena/${room_id}/output
${base_directory}/${contest_name}/map
比赛类似。

2024-04-04 15:39 UTC, zzdhybthu commented
> 还有关于几个需要手动调节的变量： 一个是服务器存放的最大文件数目。目前删文件的逻辑是，会把可执行文件长期存储在code/team_id目录下，每次开天梯对战时，先从cos下载不存在的文件，然后检查文件总数，如果文件数目超过x，删除当前比赛不使用且最古老的y个文件。x和y需要手动调节。 一个是比赛是否开放观战端口,目前天梯默认开放，比赛默认不开放。开放的话会启动envoy容器，并更新port。应该得看情况调节。 还有 memory 限制，目前延续了去年的配置。 以及比赛最长时间、容器强制销毁时间等

开赛前会把code里的文件复制到roomid对应的 resource 文件夹里。结果出来后roomid文件夹里的内容都会删掉。

2024-04-05 09:44 UTC, FranGuam commented
> 代码可能有些复杂。没写注释。可以把console.debug和log中的内容以及变量的命名作为注释看待。代码比去年的版本多出来不少的原因在于通用性提高了很多，还有就是需要检查的内容也很多。理论上现在可以支持任意多队伍、任意不同的teamlabel，任意不同的playerlabel打混战（）

woc，牛的

2024-04-05 09:55 UTC, FranGuam commented
我还没有看代码，不过有个问题我之前没有讲清楚：直播和envoy不是绑定关系。直播指的是暴露docker端口，任何人拿到合适的比赛工程代码+客户端都可以通过ip+端口来与我们服务器上的docker进行grpc通信，从而实现数据实时传输的直播功能。之所以提到envoy，是因为我们希望在网页上就能看到直播，而不需要用电脑运行工程代码这么繁重，手机就可以接入。然而，grpc不支持在网页端直接协议请求，而是要求使用grpc-web作为兼容层，由envoy进行转发。实质上是网页与服务器采用http通信，而envoy将其翻译为grpc与docker代理通信。所以，要实现这一功能，后端需要在启动比赛镜像的同时（略早）启动一个envoy镜像，具体配置文件我已经做过测试，这次部会可以与你细说。

2024-04-06 14:01 UTC, xiangmy21 requested changes
天神下凡！！！💃💃💃🥰🥰🥰😍😍😍✌️✌️🥵🥵

2024-04-09 11:14 UTC, xiangmy21 approved these changes

2024-04-09 11:14 UTC, merged