Upgrade dependency packages and clean up code
eesast/api pull request #1348
Opened 2024-05-16 15:24 UTC by zzdhybthu

2024-05-16 18:44 UTC, FranGuam requested changes
这速度很神，还可以尝试修复一下自动更新依赖。主要修改`renovate.json`和`mergify.yml`，可以与前端仓库对比着看

2024-05-16 18:44 UTC, FranGuam commented on README.md
> +#### `yarn install --registry https://registry.yarnpkg.com`
可以在`package.json`中设置`preinstall`指令来指定软件源，更方便一些

2024-05-17 07:17 UTC, zzdhybthu commented on README.md
> +#### `yarn install --registry https://registry.yarnpkg.com`
好的

2024-05-17 16:17 UTC, zzdhybthu commented on README.md
> +#### `yarn install --registry https://registry.yarnpkg.com`
目前未完全更新的两个包: eslint 最新版本 9.2.0 和 nodejs 版本不匹配，更新不了，只更新到了8.57.0
graphql-request 最新版 7.0.1 会出现 import 失败的问题（在尝试修改后语法检查通过了但是 yarn start 仍然报这个错），看了官网也没找到有用的解决方案，只更新到了 6.1.0

2024-05-17 16:17 UTC, zzdhybthu commented on README.md
> +#### `yarn install --registry https://registry.yarnpkg.com`
启用 auto update 的话是不是会导致出现两个通不过 check 的 pr？

2024-05-17 16:39 UTC, xiangmy21 approved these changes
伟大，无需多言😌
先过了，这周部会的时候看看那两个是什么问题

2024-05-17 16:40 UTC, merged